### PR TITLE
Remove CSR check from deploy-config

### PR DESCRIPTION
**Pull request by chickenbeef**
*Issue #, if available:*

When trying to build the project as per the instructions in the README, the installation goes into an infinite loop waiting for a CSR.

The CSR creation was removed from 0.3.0:

> Use in-cluster=false so that the webhook reloads certificates from the filesystem rather than creating CSRs to request certificates (using CSRs is now deprecated and will not work versions later than v0.3.0).

```bash
$ make cluster-up IMAGE=amazon/amazon-eks-pod-identity-webhook:latest
...
mutatingwebhookconfiguration.admissionregistration.k8s.io/pod-identity-webhook configured
until kubectl get csr -o \
		jsonpath='{.items[?(@.spec.username=="system:serviceaccount:default:pod-identity-webhook")].metadata.name}' | \
		grep -m 1 "csr-"; \
		do echo "Waiting for CSR to be created" && sleep 1 ; \
	done
Waiting for CSR to be created
....
Waiting for CSR to be created
```

*Description of changes:*

This PR updates the makefile to align with the CSR removal introduced in 0.3.0.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dims** [comment]
@chickenbeef wanna pick the other change from https://github.com/aws/amazon-eks-pod-identity-webhook/pull/150 as well?

**Comment by chickenbeef** [comment]
@dims definitely, I overlooked that.

Updated the `prep-config`, `delete-config` and removed the `hack/webhook-patch-ca-bundle.sh` as it's no longer needed.

```console
$ make cluster-up IMAGE=amazon/amazon-eks-pod-identity-webhook:latest
Deploying into active cluster...
...
Applying configuration to active cluster...
kubectl apply -f deploy/auth.yaml
serviceaccount/pod-identity-webhook created
role.rbac.authorization.k8s.io/pod-identity-webhook created
rolebinding.rbac.authorization.k8s.io/pod-identity-webhook created
clusterrole.rbac.authorization.k8s.io/pod-identity-webhook created
clusterrolebinding.rbac.authorization.k8s.io/pod-identity-webhook created
kubectl apply -f deploy/deployment.yaml
deployment.apps/pod-identity-webhook created
clusterissuer.cert-manager.io/selfsigned created
certificate.cert-manager.io/pod-identity-webhook created
kubectl apply -f deploy/service.yaml
service/pod-identity-webhook created
```

Down:

```console
$ make cluster-down
Tearing down mutating controller and associated resources...
kubectl delete -f deploy/service.yaml
service "pod-identity-webhook" deleted
kubectl delete -f deploy/deployment.yaml
deployment.apps "pod-identity-webhook" deleted
clusterissuer.cert-manager.io "selfsigned" deleted
certificate.cert-manager.io "pod-identity-webhook" deleted
kubectl delete -f deploy/auth.yaml
serviceaccount "pod-identity-webhook" deleted
role.rbac.authorization.k8s.io "pod-identity-webhook" deleted
rolebinding.rbac.authorization.k8s.io "pod-identity-webhook" deleted
clusterrole.rbac.authorization.k8s.io "pod-identity-webhook" deleted
clusterrolebinding.rbac.authorization.k8s.io "pod-identity-webhook" deleted
kubectl delete secret pod-identity-webhook-cert
secret "pod-identity-webhook-cert" deleted
```

**Review by dims — APPROVED** [review]
LGTM

**Comment by dims** [comment]
thanks @chickenbeef

**Pull request merged**
